# Generated by Django 4.2.30 on 2026-07-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment_enrollment_unique_user_course_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_count',
        ),
    ]
