# Generated by Django 4.2.30 on 2026-07-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_students_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
